name: weather

on:
    ## schedules can be verry deplayed. up to minutes. 
    schedule:
      - cron: '0 12 * * *'
  
    # Allows you to run this workflow manually from the Actions tab
    ## does not interfere with schedules
    workflow_dispatch:

jobs:
    GetWeather:
        runs-on: ubuntu-latest

        steps:
            - name: checkout repo content
              uses: actions/checkout@v4 

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10' #install the python needed
                cache: 'pip'

            - name: Run Bash Script
              run: |
                chmod +x ./weather/run.bash 
                ./weather/run.bash 
              env: 
                TEST_SECRET: ${{ secrets.TEST_SECRET_USAGE }}
                PAT: ${{ secrets.PAT }}
                W_KEY: ${{ secrets.W_KEY }}
                GS_AUTH: ${{ secrets.GS_AUTH }}
                STATION_NAME: ${{ vars.STATION_NAME }}
                GOOGLE_SHEET: ${{ vars.GOOGLE_SHEET }}
                GOOGLE_WORK_SHEET: ${{ vars.GOOGLE_WORK_SHEET }}
